services:
  - type: web
    name: synctune
    runtime: node
    plan: free
    buildCommand: npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o ./yt-dlp && chmod +x ./yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
